name: "PRODUCTION ENV: Snowflake Terraform Demo Workflow"

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  deploy-terraform-prod:
    name: "Deploy Terraform plan on Prod"
    runs-on: ubuntu-latest
    permissions:
      contents: read               
      id-token: write              
      pull-requests: write         

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Authenticate to Google Cloud
      - id: auth
        name: "Authenticate to Google Cloud"
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        id: init
        run: |
          # If you use per-env backend.hcl, add: -reconfigure -backend-config=backend.hcl
          terraform -chdir=./prod init

      - name: Terraform Format
        id: fmt
        run: terraform -chdir=./prod fmt -recursive -check

      - name: Terraform Validate
        id: validate
        run: terraform -chdir=./prod validate -no-color

      - name: Terraform Plan on Prod for PR
        id: plan
        if: github.event_name == 'pull_request'
        continue-on-error: true
        env:
          TF_VAR_gcs_bucket: ${{ secrets.GCS_BUCKET }}
          TF_VAR_snowflake_private_key: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}
          TF_VAR_snowflake_private_key_passphrase: ${{ secrets.SNOWFLAKE_PASSPHRASE }}
          TF_VAR_snowflake_username: ${{ secrets.SNOWFLAKE_USERNAME }}
          TF_VAR_snowflake_account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          TF_VAR_snowflake_role: ${{ secrets.SNOWFLAKE_ROLE }}
        run: terraform -chdir=./prod plan -no-color -input=false

      - name: Update Pull Request
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        env:
          PLAN: "${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`terraform
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        id: apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          TF_VAR_gcs_bucket: ${{ secrets.GCS_BUCKET }}
          TF_VAR_snowflake_private_key: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}
          TF_VAR_snowflake_private_key_passphrase: ${{ secrets.SNOWFLAKE_PASSPHRASE }}
          TF_VAR_snowflake_username: ${{ secrets.SNOWFLAKE_USERNAME }}
          TF_VAR_snowflake_account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          TF_VAR_snowflake_role: ${{ secrets.SNOWFLAKE_ROLE }}
        run: terraform -chdir=./prod apply -auto-approve -input=false
